name: Programming Languages (CMP321) Labs

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Testing Lab 1 Exercise 1
      run: python3 /home/runner/work/CMP321/CMP321/Lab1/Exercise1.py
    - name: Testing Lab 1 Exercise 2
      run: python3 /home/runner/work/CMP321/CMP321/Lab1/Exercise2.py
    - name: Testing Lab 1 Exercise 3
      run: python3 /home/runner/work/CMP321/CMP321/Lab1/Exercise3.py
    - name: Testing Lab 1 Exercise 4
      run: python3 /home/runner/work/CMP321/CMP321/Lab1/Exercise4.py
    - name: Testing Lab 1 Exercise 5
      run: python3 /home/runner/work/CMP321/CMP321/Lab1/Exercise5.py

    - name: Testing Lab 2 Exercise 1
      run: python3 /home/runner/work/CMP321/CMP321/Lab2/exercise1.py
    - name: Testing Lab 2 Exercise 2
      run: python3 /home/runner/work/CMP321/CMP321/Lab2/exercise2.py
    - name: Testing Lab 2 Exercise 3
      run: python3 /home/runner/work/CMP321/CMP321/Lab2/exercise3.py

    - name: Testing Lab 3 Exercise 1
      run: python3 /home/runner/work/CMP321/CMP321/Lab3/exercise1.py
    - name: Testing Lab 3 Exercise 2
      run: python3 /home/runner/work/CMP321/CMP321/Lab3/exercise2.py
    - name: Testing Lab 3 Exercise 3
      run: python3 /home/runner/work/CMP321/CMP321/Lab3/exercise3.py
    - name: Testing Lab 3 Exercise 4
      run: python3 /home/runner/work/CMP321/CMP321/Lab3/exercise4.py
    
    - name: Testing Lab 4 Exercise 1
      run: python3 /home/runner/work/CMP321/CMP321/Lab4/exercise1.py
    - name: Testing Lab 4 Exercise 2
      run: python3 /home/runner/work/CMP321/CMP321/Lab4/exercise2.py
    - name: Testing Lab 4 Exercise 3
      run: python3 /home/runner/work/CMP321/CMP321/Lab4/exercise3.py
    - name: Testing Lab 4 Exercise 4
      run: python3 /home/runner/work/CMP321/CMP321/Lab4/exercise4.py
    - name: Testing Lab 4 Exercise 5
      run: python3 /home/runner/work/CMP321/CMP321/Lab4/exercise5.py
